### ISSUE TITLE
Fails close to the end. Unsure if it is due to the closest server it connects to

### ISSUE THREAD

**Issue by SuperTrembler** [MysticRyuujin/guac-install#26]
Fails for me in the end of the script;
https://pastebin.com/yDt8LhL9

**Comment by MysticRyuujin** [comment]
I think I fixed it but I'm on mobile, and a little drunk

**Comment by SuperTrembler** [comment]
Not to ruin your buzz, but it is still failing for me :(
https://pastebin.com/V2iQn8x4

**Comment by MysticRyuujin** [comment]
Uhhhh, try again? I obviously need to fix this when I get back to a computer, it should be failing after the download fails but it doesn't... Bah, but I changed the variable again...

**Comment by SuperTrembler** [comment]
Sorry, same still.
Like the other guy, your response time is amazing, but seriously -  go enjoy your saturday! :)

**Comment by mgithens1** [comment]
Mine failed at same point.  Ubuntu 16.04 updated.  

Lemme know if there is any digging I can do to help.

**Comment by SuperTrembler** [comment]
Install works fine now, but I cannot get RDP to work. SSH and VNC works like a charm.
Looks to be something with freerdp as it does not work from command line either

**Comment by MysticRyuujin** [comment]
Use NLA as the encryption method, and click "ignore server certificate" that's usually all it requires...

**Comment by SuperTrembler** [comment]
It wont work with any of them, but then again it wont work from the command line so its most likely not related to the script

**Comment by MysticRyuujin** [comment]
Can you RDP to the machine from another windows machine? RDP only works for Windows Pro (as a destination) and you have to have it enabled, allowed via firewall, and be an authorized RDP user account. What OS? I did a fresh install from 16.0.4 last night testing this stuff and I was able to RDP to a Server 2016 box

**Comment by SuperTrembler** [comment]
Yeah its server 2016 with TLS enabled for RDP, works fine from windows rdp clients.
Running guacamole on a fresh debian install with only the LXDE package.

Spinning up a fresh lubuntu VM to test on now

**Comment by SuperTrembler** [comment]
Lubuntu stops with the following;
Package freerdp is a virtual package provided by:
  freerdp2-x11 2.0.0~git20170725.1.1648deb+dfsg1-1
  freerdp2-shadow-x11 2.0.0~git20170725.1.1648deb+dfsg1-1
  freerdp-x11 1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1
You should explicitly select one to install.

**Comment by SuperTrembler** [comment]
So I went back to the Debian with only LXDE, the version installed by the script 1.0.0 does not work from the command line, but 2.0.0 does

**Comment by MysticRyuujin** [comment]
What's the apt package name? I can modify it for stretch to install 2 pretty easily. I don't know how to identify Lubuntu off the top of my head to customize that package, but I can look into it's when I have time...

**Comment by SuperTrembler** [comment]
For Lubuntu its freerdp2-x11 2.0.0git20170725.1.1648deb+dfsg1-1
For Debian there only seems to be the one package

**Comment by MysticRyuujin** [comment]
What version of Debian did you use?

I spun up a Debian 9 (stretch) and looked at the apt-cache and it shows version 1.1 which is the same version as Ubuntu and they're working fine...

**Comment by MysticRyuujin** [comment]
Interestingly if you look at the documentation it doesn't say `freerdp-x11` needs to be installed at all. I changed it to "freerdp-x11" to fix the prompt Lubuntu is giving but I don't think that's the issue. The documentation only states that we need the development package `libfreerdp-dev`

I wonder if Lubuntu or Debian have not-supported versions of that package? Perhaps when you installed freerdp2-x11 it resolved some other issue?

**Comment by SuperTrembler** [comment]
I ended up going with Lubuntu 16 LTS and it worked like a charm.
Also figured out I had to enter username and password on the RDP connection, I was expecting a login screen if it wasn't filled out... so for all I know it was working all the time? 

Sorry for wasting your time
